#!/usr/bin/env python3
"""Generate seed-puzzles.json with literal, easy-to-decode emoji puzzles.

Rule: every emoji maps directly to a word in the answer. No filler emojis.
- Easy: 2 emojis (max 3)
- Medium: 2-4 emojis
- Hard: 3-5 emojis
"""

import json

# Format: (emoji_clue, canonical_answer, accepted_answers, hint, difficulty, category)
# accepted_answers is a list of lowercase variations

MOVIES = [
    # === EASY (17) ===
    ("🕷️👨", "Spider-Man", ["spider-man","spiderman","spider man"], "Spider + Man", "easy", "superhero", 1),
    ("🦇👨", "Batman", ["batman","the batman"], "Bat + Man", "easy", "superhero", 2),
    ("⭐⚔️", "Star Wars", ["star wars"], "Star + Wars", "easy", "sci-fi", 3),
    ("🐜👨", "Ant-Man", ["ant-man","antman","ant man"], "Ant + Man", "easy", "superhero", 4),
    ("🦁👑", "The Lion King", ["the lion king","lion king"], "Lion + King", "easy", "animated", 5),
    ("👻👊", "Ghostbusters", ["ghostbusters","ghost busters"], "Ghost + Busters", "easy", "comedy", 6),
    ("🔍🐠", "Finding Nemo", ["finding nemo"], "Finding + Fish", "easy", "animated", 7),
    ("🧙‍♂️💍", "Lord of the Rings", ["lord of the rings","lotr"], "Wizard + Ring", "easy", "fantasy", 8),
    ("🦈", "Jaws", ["jaws"], "Shark movie", "easy", "thriller", 9),
    ("⬆️🏠", "Up", ["up"], "Up + House", "easy", "animated", 10),
    ("🐀👨‍🍳", "Ratatouille", ["ratatouille"], "Rat + Chef", "easy", "animated", 11),
    ("🧊❄️👸", "Frozen", ["frozen"], "Ice + Snow + Princess", "easy", "animated", 12),
    ("🏴‍☠️🌊", "Pirates of the Caribbean", ["pirates of the caribbean"], "Pirates + Ocean", "easy", "adventure", 13),
    ("🧸📖", "Toy Story", ["toy story"], "Toy + Story", "easy", "animated", 14),
    ("🐝🎬", "Bee Movie", ["bee movie"], "Bee + Movie", "easy", "animated", 15),
    ("🦈🌪️", "Sharknado", ["sharknado"], "Shark + Tornado", "easy", "action", 16),
    ("🌊🌍", "Waterworld", ["waterworld","water world"], "Water + World", "easy", "sci-fi", 17),
    # === MEDIUM (17) ===
    ("🧊🧓", "Ice Age", ["ice age"], "Ice + Age", "medium", "animated", 1),
    ("👑🦍", "King Kong", ["king kong"], "King + Gorilla", "medium", "action", 2),
    ("🧹🧙‍♂️⚡", "Harry Potter", ["harry potter"], "Broom + Wizard + Lightning", "medium", "fantasy", 3),
    ("🐉🏋️", "How to Train Your Dragon", ["how to train your dragon"], "Dragon + Training", "medium", "animated", 4),
    ("👸🌹👹", "Beauty and the Beast", ["beauty and the beast"], "Princess + Rose + Beast", "medium", "animated", 5),
    ("🤖👮", "RoboCop", ["robocop","robo cop"], "Robot + Cop", "medium", "sci-fi", 6),
    ("🌊👨🔱", "Aquaman", ["aquaman","aqua man"], "Water + Man + Trident", "medium", "superhero", 7),
    ("🥋🐼", "Kung Fu Panda", ["kung fu panda"], "Martial arts + Panda", "medium", "animated", 8),
    ("🔙⏰", "Back to the Future", ["back to the future"], "Back + Clock", "medium", "sci-fi", 9),
    ("🏎️💨😡", "Fast and Furious", ["fast and furious","the fast and the furious"], "Fast + Furious", "medium", "action", 10),
    ("👽📱", "E.T.", ["e.t.","et","e.t. the extra terrestrial"], "Alien + Phone home", "medium", "sci-fi", 11),
    ("❌👨👩", "X-Men", ["x-men","xmen","x men"], "X + Men", "medium", "superhero", 12),
    ("🐷🐷🐷🐺", "The Three Little Pigs", ["the three little pigs","three little pigs"], "Three pigs + Wolf", "medium", "fairy tale", 13),
    ("⚡🏃", "The Flash", ["the flash","flash"], "Lightning + Runner", "medium", "superhero", 14),
    ("💀🏊", "Deadpool", ["deadpool","dead pool"], "Dead + Pool", "medium", "superhero", 15),
    ("🚢🧊", "Titanic", ["titanic"], "Ship + Iceberg", "medium", "drama", 16),
    ("🧬🦕", "Jurassic Park", ["jurassic park"], "DNA + Dinosaur", "medium", "sci-fi", 17),
    # === HARD (16) ===
    ("🕶️💊", "The Matrix", ["the matrix","matrix"], "Sunglasses + Pill", "hard", "sci-fi", 1),
    ("🗡️🏃‍♂️", "Blade Runner", ["blade runner"], "Blade + Runner", "hard", "sci-fi", 2),
    ("⏰🍊", "A Clockwork Orange", ["a clockwork orange","clockwork orange"], "Clock + Orange", "hard", "drama", 3),
    ("🤫🐑🐑", "Silence of the Lambs", ["the silence of the lambs","silence of the lambs"], "Silence + Lambs", "hard", "thriller", 4),
    ("🌍⚔️🧟", "World War Z", ["world war z"], "World + War + Zombie", "hard", "horror", 5),
    ("🏠👻", "Haunted Mansion", ["haunted mansion","the haunted mansion"], "House + Ghost", "hard", "horror", 6),
    ("🐦📦", "Bird Box", ["bird box"], "Bird + Box", "hard", "thriller", 7),
    ("🕷️👨🌀", "Spider-Man: Into the Spider-Verse", ["into the spider verse","spider-man into the spider-verse"], "Spider-Man + Multiverse", "hard", "animated", 8),
    ("🌙💡", "Moonlight", ["moonlight"], "Moon + Light", "hard", "drama", 9),
    ("👸📓", "The Princess Diaries", ["the princess diaries","princess diaries"], "Princess + Diary", "hard", "comedy", 10),
    ("👦🐺", "Teen Wolf", ["teen wolf"], "Boy + Wolf", "hard", "comedy", 11),
    ("🔨👇", "Nailed It", ["nailed it"], "Hammer + Down", "hard", "comedy", 12),
    ("🌙👑", "Moonlight Kingdom", ["moonrise kingdom","moonlight kingdom"], "Moon + Kingdom", "hard", "drama", 13),
    ("🐉🔥🏰", "Reign of Fire", ["reign of fire"], "Dragon + Fire + Castle", "hard", "action", 14),
    ("🦸‍♂️🔨⚡", "Thor", ["thor"], "Hero + Hammer + Lightning", "hard", "action", 15),
    ("🧱🧱🐉", "Great Wall", ["the great wall","great wall"], "Wall + Wall + Dragon", "hard", "action", 16),
]

SONGS = [
    # === EASY (17) ===
    ("☀️🌻", "Sunflower", ["sunflower"], "Sun + Flower", "easy", "pop", 1),
    ("🌙💡", "Moonlight", ["moonlight"], "Moon + Light", "easy", "pop", 2),
    ("🔥🔥🔥", "Fire", ["fire"], "Three fires", "easy", "pop", 3),
    ("☀️😊", "Sunshine", ["sunshine"], "Sun + Shine", "easy", "pop", 4),
    ("🐊🪨", "Crocodile Rock", ["crocodile rock"], "Crocodile + Rock", "easy", "rock", 5),
    ("💎💎", "Diamonds", ["diamonds"], "Diamonds", "easy", "pop", 6),
    ("🍋🌳", "Lemon Tree", ["lemon tree"], "Lemon + Tree", "easy", "pop", 7),
    ("👏🖐️", "Clap Your Hands", ["clap your hands"], "Clap + Hands", "easy", "pop", 8),
    ("🌊👨", "Ocean Man", ["ocean man"], "Ocean + Man", "easy", "rock", 9),
    ("🔔🔔🔔", "Jingle Bells", ["jingle bells"], "Bells ringing", "easy", "holiday", 10),
    ("🚀👨", "Rocket Man", ["rocket man"], "Rocket + Man", "easy", "rock", 11),
    ("💜🌧️", "Purple Rain", ["purple rain"], "Purple + Rain", "easy", "pop", 12),
    ("💔🏨", "Heartbreak Hotel", ["heartbreak hotel"], "Heartbreak + Hotel", "easy", "rock", 13),
    ("🧊🧊👶", "Ice Ice Baby", ["ice ice baby"], "Ice + Ice + Baby", "easy", "hiphop", 14),
    ("⭐👨", "Starman", ["starman"], "Star + Man", "easy", "rock", 15),
    ("🌙🚶", "Moonwalker", ["moonwalker","moonwalk"], "Moon + Walk", "easy", "pop", 16),
    ("🔥👧", "Girl on Fire", ["girl on fire"], "Fire + Girl", "easy", "pop", 17),
    # === MEDIUM (17) ===
    ("🎸🪨⭐", "Rock Star", ["rock star","rockstar"], "Rock + Star", "medium", "rock", 1),
    ("👶🔙", "Baby Come Back", ["baby come back"], "Baby + Come back", "medium", "pop", 2),
    ("💃🔥", "Dance on Fire", ["dance on fire"], "Dance + Fire", "medium", "rock", 3),
    ("🍓🍓🌾", "Strawberry Fields", ["strawberry fields","strawberry fields forever"], "Strawberry + Fields", "medium", "rock", 4),
    ("⚡🔨", "Thunderstruck", ["thunderstruck"], "Thunder + Struck", "medium", "rock", 5),
    ("📻👤", "Radiohead", ["radiohead"], "Radio + Head", "medium", "rock", 6),
    ("💜🌫️", "Purple Haze", ["purple haze"], "Purple + Haze", "medium", "rock", 7),
    ("🌙💃", "Dancing in the Moonlight", ["dancing in the moonlight"], "Moon + Dancing", "medium", "pop", 8),
    ("⬛🐦", "Blackbird", ["blackbird"], "Black + Bird", "medium", "rock", 9),
    ("🌊👁️👁️", "Ocean Eyes", ["ocean eyes"], "Ocean + Eyes", "medium", "pop", 10),
    ("🪜☁️😇", "Stairway to Heaven", ["stairway to heaven"], "Stairs + Cloud + Angel", "medium", "rock", 11),
    ("😈🔔🔔", "Hells Bells", ["hells bells"], "Devil + Bells", "medium", "rock", 12),
    ("🏔️🪨☀️", "Rocky Mountain High", ["rocky mountain high"], "Rocky + Mountain + High", "medium", "rock", 13),
    ("⬛🪄👩", "Black Magic Woman", ["black magic woman"], "Black + Magic + Woman", "medium", "rock", 14),
    ("🏨🌴", "Hotel California", ["hotel california"], "Hotel + Palm trees", "medium", "rock", 15),
    ("🛣️😈", "Highway to Hell", ["highway to hell"], "Highway + Devil", "medium", "rock", 16),
    ("✈️🦋", "Fly Away", ["fly away"], "Fly + Butterfly", "medium", "rock", 17),
    # === HARD (16) ===
    ("🔔❓☠️", "For Whom the Bell Tolls", ["for whom the bell tolls"], "Bell + Question + Death", "hard", "rock", 1),
    ("🐕☀️", "Dog Days", ["dog days","dog days are over"], "Dog + Sun", "hard", "pop", 2),
    ("🌈🔚🪙", "Gold at the End of the Rainbow", ["gold at the end of the rainbow"], "Rainbow + End + Gold", "hard", "pop", 3),
    ("👻🎪", "Circus of the Dead", ["circus of the dead"], "Ghost + Circus", "hard", "rock", 4),
    ("❄️☕", "Cold Brew", ["cold brew"], "Snowflake + Coffee", "hard", "pop", 5),
    ("🔫🌹", "Guns N' Roses", ["guns n roses","guns and roses","guns n' roses"], "Gun + Rose", "hard", "rock", 6),
    ("🌧️💧😢", "Crying in the Rain", ["crying in the rain"], "Rain + Tears", "hard", "pop", 7),
    ("🌙🌊", "Moonlight Sonata", ["moonlight sonata"], "Moon + Waves", "hard", "classical", 8),
    ("💔🗡️", "Heartbreaker", ["heartbreaker"], "Heart + Break", "hard", "rock", 9),
    ("☁️🔢9️⃣", "Cloud 9", ["cloud 9","cloud nine"], "Cloud + Nine", "hard", "pop", 10),
    ("🐝🧎", "Honey", ["honey"], "Bee + Kneel", "hard", "pop", 11),
    ("👑👸", "Queen", ["queen"], "Crown + Princess", "hard", "rock", 12),
    ("🏃💨", "Run", ["run"], "Running + Wind", "hard", "pop", 13),
    ("🌃🌙⏰", "Midnight", ["midnight"], "Night + Moon + Clock", "hard", "pop", 14),
    ("🔥❤️", "Burning Love", ["burning love"], "Fire + Heart", "hard", "rock", 15),
    ("🚗🚗", "Drive", ["drive"], "Cars driving", "hard", "pop", 16),
]

FOOD = [
    # === EASY (17) ===
    ("🍳🥞", "Pancake", ["pancake","pancakes"], "Pan + Cake", "easy", "breakfast", 1),
    ("🔥🐕", "Hotdog", ["hotdog","hot dog"], "Hot + Dog", "easy", "fast food", 2),
    ("💥🌽", "Popcorn", ["popcorn","pop corn"], "Pop + Corn", "easy", "snack", 3),
    ("🧈🥛", "Buttermilk", ["buttermilk"], "Butter + Milk", "easy", "dairy", 4),
    ("🍓🎂", "Strawberry Cake", ["strawberry cake"], "Strawberry + Cake", "easy", "dessert", 5),
    ("🧀🍔", "Cheeseburger", ["cheeseburger","cheese burger"], "Cheese + Burger", "easy", "fast food", 6),
    ("🥜🧈", "Peanut Butter", ["peanut butter"], "Peanut + Butter", "easy", "spread", 7),
    ("🧊☕", "Iced Coffee", ["iced coffee"], "Ice + Coffee", "easy", "drink", 8),
    ("🍌🍞", "Banana Bread", ["banana bread"], "Banana + Bread", "easy", "baked", 9),
    ("🍎🥧", "Apple Pie", ["apple pie"], "Apple + Pie", "easy", "dessert", 10),
    ("🧅🔗", "Onion Rings", ["onion rings"], "Onion + Rings", "easy", "snack", 11),
    ("🥚🍳", "Fried Egg", ["fried egg"], "Egg + Frying pan", "easy", "breakfast", 12),
    ("🍫🍪", "Chocolate Chip Cookie", ["chocolate chip cookie","chocolate cookie"], "Chocolate + Cookie", "easy", "dessert", 13),
    ("🐔🍗", "Chicken Wings", ["chicken wings"], "Chicken + Drumstick", "easy", "meat", 14),
    ("🍍🎂", "Pineapple Cake", ["pineapple cake","pineapple upside down cake"], "Pineapple + Cake", "easy", "dessert", 15),
    ("🍯🎂", "Honeycake", ["honeycake","honey cake"], "Honey + Cake", "easy", "dessert", 16),
    ("🫘🌮", "Bean Burrito", ["bean burrito"], "Bean + Burrito", "easy", "mexican", 17),
    # === MEDIUM (17) ===
    ("🌽🍞", "Cornbread", ["cornbread","corn bread"], "Corn + Bread", "medium", "baked", 1),
    ("🧀🍟", "Cheese Fries", ["cheese fries"], "Cheese + Fries", "medium", "snack", 2),
    ("🌿🍵", "Green Tea", ["green tea"], "Green + Tea", "medium", "drink", 3),
    ("🐟🌮", "Fish Taco", ["fish taco","fish tacos"], "Fish + Taco", "medium", "mexican", 4),
    ("🍊🐔", "Orange Chicken", ["orange chicken"], "Orange + Chicken", "medium", "chinese", 5),
    ("🥛🫗🍦", "Milkshake", ["milkshake","milk shake"], "Milk + Shake", "medium", "drink", 6),
    ("🍣🌀", "Sushi Roll", ["sushi roll"], "Sushi + Roll", "medium", "japanese", 7),
    ("☕🎂", "Coffee Cake", ["coffee cake"], "Coffee + Cake", "medium", "dessert", 8),
    ("🫐🥞", "Blueberry Pancakes", ["blueberry pancakes","blueberry pancake"], "Blueberry + Pancakes", "medium", "breakfast", 9),
    ("🍿🧈", "Buttered Popcorn", ["buttered popcorn"], "Butter + Popcorn", "medium", "snack", 10),
    ("🧈🍗", "Butter Chicken", ["butter chicken"], "Butter + Chicken", "medium", "indian", 11),
    ("🧄🍞", "Garlic Bread", ["garlic bread"], "Garlic + Bread", "medium", "baked", 12),
    ("🍋💧", "Lemonade", ["lemonade"], "Lemon + Water", "medium", "drink", 13),
    ("🥑🍞", "Avocado Toast", ["avocado toast"], "Avocado + Toast", "medium", "breakfast", 14),
    ("🧇🍦", "Waffle Cone", ["waffle cone"], "Waffle + Ice cream", "medium", "dessert", 15),
    ("🍄🍕", "Mushroom Pizza", ["mushroom pizza"], "Mushroom + Pizza", "medium", "italian", 16),
    ("🧊🍵", "Iced Tea", ["iced tea"], "Ice + Tea", "medium", "drink", 17),
    # === HARD (16) ===
    ("🌶️🍫", "Chili Chocolate", ["chili chocolate"], "Chili + Chocolate", "hard", "dessert", 1),
    ("🦞🍜", "Lobster Bisque", ["lobster bisque"], "Lobster + Soup", "hard", "seafood", 2),
    ("🍳🥚🥓", "Eggs Benedict", ["eggs benedict"], "Egg + Bacon", "hard", "breakfast", 3),
    ("🌶️🥩🫘", "Chili Con Carne", ["chili con carne"], "Chili + Meat + Beans", "hard", "mexican", 4),
    ("🦐🍝", "Shrimp Pasta", ["shrimp pasta"], "Shrimp + Pasta", "hard", "italian", 5),
    ("🧊🍵🟢", "Iced Matcha", ["iced matcha"], "Ice + Tea + Green", "hard", "drink", 6),
    ("🫔🧀", "Quesadilla", ["quesadilla"], "Tortilla + Cheese", "hard", "mexican", 7),
    ("🥐☕", "Croissant and Coffee", ["croissant and coffee"], "Croissant + Coffee", "hard", "french", 8),
    ("🍋🥧", "Lemon Meringue Pie", ["lemon meringue pie"], "Lemon + Pie", "hard", "dessert", 9),
    ("🥩🔥", "Steak", ["steak","grilled steak"], "Meat + Fire", "hard", "meat", 10),
    ("🌰🍞", "Chestnut Bread", ["chestnut bread"], "Chestnut + Bread", "hard", "baked", 11),
    ("🐝🧈🧅", "Honey Butter Onion", ["honey butter onion"], "Honey + Butter + Onion", "hard", "condiment", 12),
    ("🍫⛲", "Chocolate Fountain", ["chocolate fountain"], "Chocolate + Fountain", "hard", "dessert", 13),
    ("🥝🍦", "Kiwi Sorbet", ["kiwi sorbet","kiwi ice cream"], "Kiwi + Ice cream", "hard", "dessert", 14),
    ("🔥🥜", "Roasted Peanuts", ["roasted peanuts"], "Fire + Peanuts", "hard", "snack", 15),
    ("🥥🍚", "Coconut Rice", ["coconut rice"], "Coconut + Rice", "hard", "asian", 16),
]

ANIMALS = [
    # === EASY (17) ===
    ("⭐🐟", "Starfish", ["starfish","star fish"], "Star + Fish", "easy", "sea", 1),
    ("🐱🐟", "Catfish", ["catfish","cat fish"], "Cat + Fish", "easy", "sea", 2),
    ("🐂🐕", "Bulldog", ["bulldog","bull dog"], "Bull + Dog", "easy", "dog", 3),
    ("🌊🐢", "Sea Turtle", ["sea turtle"], "Sea + Turtle", "easy", "sea", 4),
    ("🦁🐟", "Lionfish", ["lionfish","lion fish"], "Lion + Fish", "easy", "sea", 5),
    ("🐕🐟", "Dogfish", ["dogfish","dog fish"], "Dog + Fish", "easy", "sea", 6),
    ("🐝🐝", "Bumblebee", ["bumblebee","bumble bee"], "Bee + Bee", "easy", "insect", 7),
    ("🐴🪰", "Horsefly", ["horsefly","horse fly"], "Horse + Fly", "easy", "insect", 8),
    ("🔥🪰", "Firefly", ["firefly","fire fly"], "Fire + Fly", "easy", "insect", 9),
    ("🐍👑", "King Cobra", ["king cobra"], "Snake + Crown", "easy", "reptile", 10),
    ("🐺🐕", "Wolf Dog", ["wolf dog","wolfdog"], "Wolf + Dog", "easy", "dog", 11),
    ("🐻🐱", "Bearcat", ["bearcat","bear cat"], "Bear + Cat", "easy", "mammal", 12),
    ("🗡️🐟", "Swordfish", ["swordfish","sword fish"], "Sword + Fish", "easy", "sea", 13),
    ("🐸👑", "Frog Prince", ["frog prince"], "Frog + Crown", "easy", "fairy tale", 14),
    ("🐂🐸", "Bullfrog", ["bullfrog","bull frog"], "Bull + Frog", "easy", "amphibian", 15),
    ("🌊🐴", "Seahorse", ["seahorse","sea horse"], "Sea + Horse", "easy", "sea", 16),
    ("👑🐟", "Kingfisher", ["kingfisher","king fisher"], "King + Fish", "easy", "bird", 17),
    # === MEDIUM (17) ===
    ("🧈🪰", "Butterfly", ["butterfly","butter fly"], "Butter + Fly", "medium", "insect", 1),
    ("🐜🍽️", "Anteater", ["anteater","ant eater"], "Ant + Eater", "medium", "mammal", 2),
    ("🫙🐟", "Jellyfish", ["jellyfish","jelly fish"], "Jelly + Fish", "medium", "sea", 3),
    ("⚡🐛", "Lightning Bug", ["lightning bug"], "Lightning + Bug", "medium", "insect", 4),
    ("🕷️🐒", "Spider Monkey", ["spider monkey"], "Spider + Monkey", "medium", "mammal", 5),
    ("🔥🐦", "Firebird", ["firebird","fire bird"], "Fire + Bird", "medium", "myth", 6),
    ("❄️🦊", "Arctic Fox", ["arctic fox"], "Ice + Fox", "medium", "mammal", 7),
    ("🐄🐦", "Cowbird", ["cowbird","cow bird"], "Cow + Bird", "medium", "bird", 8),
    ("🔨👤🦈", "Hammerhead Shark", ["hammerhead shark","hammerhead"], "Hammer + Head + Shark", "medium", "sea", 9),
    ("🐋🦈", "Whale Shark", ["whale shark"], "Whale + Shark", "medium", "sea", 10),
    ("🐉🪰", "Dragonfly", ["dragonfly","dragon fly"], "Dragon + Fly", "medium", "insect", 11),
    ("🌈🐍", "Rainbow Boa", ["rainbow boa"], "Rainbow + Snake", "medium", "reptile", 12),
    ("👑🐝", "Queen Bee", ["queen bee"], "Queen + Bee", "medium", "insect", 13),
    ("🐄🐟", "Cowfish", ["cowfish","cow fish"], "Cow + Fish", "medium", "sea", 14),
    ("🦂🐟", "Scorpionfish", ["scorpionfish","scorpion fish"], "Scorpion + Fish", "medium", "sea", 15),
    ("🐸🐟", "Frogfish", ["frogfish","frog fish"], "Frog + Fish", "medium", "sea", 16),
    ("👻🐟", "Ghost Fish", ["ghost fish","ghostfish"], "Ghost + Fish", "medium", "sea", 17),
    # === HARD (16) ===
    ("🖥️🦎", "Monitor Lizard", ["monitor lizard"], "Monitor + Lizard", "hard", "reptile", 1),
    ("🪸🐍", "Coral Snake", ["coral snake"], "Coral + Snake", "hard", "reptile", 2),
    ("🧂🌊🐊", "Saltwater Crocodile", ["saltwater crocodile","saltwater croc"], "Salt + Water + Croc", "hard", "reptile", 3),
    ("👻🦐", "Ghost Shrimp", ["ghost shrimp"], "Ghost + Shrimp", "hard", "sea", 4),
    ("🏜️🦎", "Gila Monster", ["gila monster"], "Desert + Lizard", "hard", "reptile", 5),
    ("📝🐦", "Secretary Bird", ["secretary bird"], "Note + Bird", "hard", "bird", 6),
    ("🧶🐻", "Woolly Bear", ["woolly bear"], "Wool + Bear", "hard", "insect", 7),
    ("🎵🐦", "Hummingbird", ["hummingbird","humming bird"], "Music + Bird", "hard", "bird", 8),
    ("🦉🦅", "Owl Eagle", ["owl eagle","eagle owl"], "Owl + Eagle", "hard", "bird", 9),
    ("👶🐍", "Baby Snake", ["baby snake"], "Baby + Snake", "hard", "reptile", 10),
    ("🐺🐟", "Wolffish", ["wolffish","wolf fish"], "Wolf + Fish", "hard", "sea", 11),
    ("🐆🐟", "Leopard Seal", ["leopard seal"], "Leopard + Fish", "hard", "sea", 12),
    ("🌲🐸", "Tree Frog", ["tree frog"], "Tree + Frog", "hard", "amphibian", 13),
    ("🐍👀", "Cobra", ["cobra"], "Snake + Eyes", "hard", "reptile", 14),
    ("🐝🍯🦡", "Honey Badger", ["honey badger"], "Bee + Honey + Badger", "hard", "mammal", 15),
    ("🦁🐜", "Ant Lion", ["ant lion","antlion"], "Lion + Ant", "hard", "insect", 16),
]

PLACES = [
    # === EASY (17) ===
    ("💧🍂", "Waterfall", ["waterfall","water fall"], "Water + Fall", "easy", "nature", 1),
    ("🌧️🌲", "Rainforest", ["rainforest","rain forest"], "Rain + Forest", "easy", "nature", 2),
    ("🌊🏖️", "Seashore", ["seashore","sea shore"], "Sea + Shore", "easy", "nature", 3),
    ("❄️⛰️", "Snow Mountain", ["snow mountain"], "Snow + Mountain", "easy", "nature", 4),
    ("🏠🌲", "Treehouse", ["treehouse","tree house"], "Tree + House", "easy", "nature", 5),
    ("🏔️🌲", "Mountain Forest", ["mountain forest"], "Mountain + Forest", "easy", "nature", 6),
    ("🏜️☀️", "Desert", ["desert"], "Desert + Sun", "easy", "nature", 7),
    ("🏝️🌴", "Island", ["island"], "Island + Palm tree", "easy", "nature", 8),
    ("🌋🔥", "Volcano", ["volcano"], "Volcano + Fire", "easy", "nature", 9),
    ("⭐🌃", "Starry Night", ["starry night"], "Star + Night", "easy", "nature", 10),
    ("🌊🏄", "Surf Beach", ["surf beach"], "Wave + Surfer", "easy", "nature", 11),
    ("🌲🏠", "Log Cabin", ["log cabin"], "Trees + House", "easy", "nature", 12),
    ("🏔️🏕️", "Mountain Camp", ["mountain camp"], "Mountain + Camp", "easy", "nature", 13),
    ("🌊🧊", "Glacier", ["glacier"], "Water + Ice", "easy", "nature", 14),
    ("🌙🌊", "Moonlit Beach", ["moonlit beach"], "Moon + Beach", "easy", "nature", 15),
    ("🌊🏖️🌴", "Tropical Beach", ["tropical beach"], "Sea + Beach + Palm", "easy", "nature", 16),
    ("🌞🌻", "Sunflower Field", ["sunflower field"], "Sun + Sunflower", "easy", "nature", 17),
    # === MEDIUM (17) ===
    ("🧊🌍", "Iceland", ["iceland"], "Ice + Land", "medium", "country", 1),
    ("🟡🪨", "Yellowstone", ["yellowstone"], "Yellow + Stone", "medium", "landmark", 2),
    ("🟡🌉", "Golden Gate", ["golden gate","golden gate bridge"], "Gold + Gate", "medium", "landmark", 3),
    ("💎👤", "Diamond Head", ["diamond head"], "Diamond + Head", "medium", "landmark", 4),
    ("🗽🏝️", "Statue of Liberty", ["statue of liberty"], "Statue + Island", "medium", "landmark", 5),
    ("❄️🌍🐧", "Antarctica", ["antarctica"], "Ice + Globe + Penguin", "medium", "continent", 6),
    ("🌊🏞️🌈", "Niagara Falls", ["niagara falls"], "Water + Falls + Rainbow", "medium", "landmark", 7),
    ("🏝️🌺🌋", "Hawaii", ["hawaii"], "Island + Flowers + Volcano", "medium", "place", 8),
    ("🗼🥐", "Paris", ["paris"], "Tower + Croissant", "medium", "city", 9),
    ("🎰🌵", "Las Vegas", ["las vegas","vegas"], "Casino + Desert", "medium", "city", 10),
    ("🏯🌸", "Kyoto", ["kyoto"], "Temple + Cherry blossom", "medium", "city", 11),
    ("🪨🏔️🏔️", "Rocky Mountains", ["rocky mountains"], "Rock + Mountains", "medium", "landmark", 12),
    ("🌴☀️🌊", "Malibu", ["malibu"], "Palm + Sun + Wave", "medium", "place", 13),
    ("🌊🏰", "Sea Castle", ["sea castle","sandcastle"], "Sea + Castle", "medium", "nature", 14),
    ("⛰️☁️", "Mountaintop", ["mountaintop","mountain top"], "Mountain + Clouds", "medium", "nature", 15),
    ("🏜️🌹", "Desert Rose", ["desert rose"], "Desert + Rose", "medium", "nature", 16),
    ("⬛🌲🌲", "Black Forest", ["black forest"], "Black + Forest", "medium", "place", 17),
    # === HARD (16) ===
    ("🐣🏝️🗿", "Easter Island", ["easter island"], "Easter + Island + Statues", "hard", "landmark", 1),
    ("🏝️🔺", "Bermuda Triangle", ["bermuda triangle"], "Island + Triangle", "hard", "landmark", 2),
    ("🏔️🦁", "Mount Kilimanjaro", ["mount kilimanjaro","kilimanjaro"], "Mountain + Lion (Africa)", "hard", "landmark", 3),
    ("🏜️🐫", "Sahara", ["sahara","sahara desert"], "Desert + Camel", "hard", "landmark", 4),
    ("🏔️☁️🧗", "Mount Everest", ["mount everest","everest"], "Mountain + Clouds + Climber", "hard", "landmark", 5),
    ("🏰🧛🦇", "Transylvania", ["transylvania"], "Castle + Vampire + Bat", "hard", "place", 6),
    ("🌋🏛️🔥", "Pompeii", ["pompeii"], "Volcano + Ruins + Fire", "hard", "landmark", 7),
    ("🐊🌿🦩", "Everglades", ["everglades","the everglades"], "Alligator + Swamp + Flamingo", "hard", "landmark", 8),
    ("💀🏜️", "Death Valley", ["death valley"], "Skull + Desert", "hard", "landmark", 9),
    ("🌊🪸🐠", "Great Barrier Reef", ["great barrier reef"], "Ocean + Coral + Fish", "hard", "landmark", 10),
    ("🏔️🌫️🏛️", "Machu Picchu", ["machu picchu"], "Mountain + Mist + Ruins", "hard", "landmark", 11),
    ("🌊🐉", "Loch Ness", ["loch ness"], "Lake + Dragon", "hard", "landmark", 12),
    ("🏰💂👑", "Buckingham Palace", ["buckingham palace"], "Castle + Guard + Crown", "hard", "landmark", 13),
    ("🧱🧱🐉", "Great Wall of China", ["great wall of china","great wall"], "Wall + Dragon", "hard", "landmark", 14),
    ("🌺🌊🏝️", "Bora Bora", ["bora bora"], "Flower + Ocean + Island", "hard", "landmark", 15),
    ("🌊⛵🏝️", "Caribbean", ["caribbean","the caribbean"], "Ocean + Sail + Island", "hard", "place", 16),
]

SPORTS = [
    # === EASY (17) ===
    ("🦶⚽", "Football", ["football"], "Foot + Ball", "easy", "sport", 1),
    ("✋⚽", "Handball", ["handball","hand ball"], "Hand + Ball", "easy", "sport", 2),
    ("🏀🥅", "Basketball", ["basketball","basket ball"], "Basket + Ball", "easy", "sport", 3),
    ("⚾", "Baseball", ["baseball","base ball"], "Baseball", "easy", "sport", 4),
    ("🏐🌊", "Beach Volleyball", ["beach volleyball"], "Volleyball + Beach", "easy", "sport", 5),
    ("⛳🏌️", "Golf", ["golf"], "Golf flag + Golfer", "easy", "sport", 6),
    ("🎾", "Tennis", ["tennis"], "Tennis ball", "easy", "sport", 7),
    ("🏊💧", "Swimming", ["swimming"], "Swimmer + Water", "easy", "sport", 8),
    ("🥊🥊", "Boxing", ["boxing"], "Boxing gloves", "easy", "sport", 9),
    ("⛷️❄️", "Skiing", ["skiing"], "Skier + Snow", "easy", "sport", 10),
    ("🛹", "Skateboarding", ["skateboarding","skating"], "Skateboard", "easy", "sport", 11),
    ("🚴💨", "Cycling", ["cycling"], "Cyclist + Wind", "easy", "sport", 12),
    ("🏈🏟️", "American Football", ["american football"], "Football + Stadium", "easy", "sport", 13),
    ("🤸", "Gymnastics", ["gymnastics"], "Gymnast", "easy", "sport", 14),
    ("🏇🐴", "Horse Racing", ["horse racing"], "Jockey + Horse", "easy", "sport", 15),
    ("🎯🏹", "Archery", ["archery"], "Target + Bow", "easy", "sport", 16),
    ("⚽🥅", "Penalty Kick", ["penalty kick","penalty"], "Ball + Goal", "easy", "sport", 17),
    # === MEDIUM (17) ===
    ("🏠🏃⚾", "Home Run", ["home run","homerun"], "Home + Run + Baseball", "medium", "sport", 1),
    ("🏄🌊", "Surfing", ["surfing","surfboard"], "Surfer + Wave", "medium", "sport", 2),
    ("🤺⚔️", "Fencing", ["fencing"], "Fencer + Swords", "medium", "sport", 3),
    ("🎳🎳", "Bowling", ["bowling"], "Bowling pins", "medium", "sport", 4),
    ("🧊🏒", "Ice Hockey", ["ice hockey","hockey"], "Ice + Hockey stick", "medium", "sport", 5),
    ("🏋️💪", "Weightlifting", ["weightlifting","weight lifting"], "Weights + Muscles", "medium", "sport", 6),
    ("🤼💪", "Wrestling", ["wrestling"], "Wrestlers + Strength", "medium", "sport", 7),
    ("🏂❄️", "Snowboarding", ["snowboarding"], "Snowboarder + Snow", "medium", "sport", 8),
    ("🏊🚴🏃", "Triathlon", ["triathlon"], "Swim + Bike + Run", "medium", "sport", 9),
    ("🧗🪨", "Rock Climbing", ["rock climbing"], "Climber + Rock", "medium", "sport", 10),
    ("🏓🏓", "Ping Pong", ["ping pong","table tennis"], "Paddles", "medium", "sport", 11),
    ("🚣‍♂️🌊", "Rowing", ["rowing"], "Rower + Water", "medium", "sport", 12),
    ("🐴🤸", "Equestrian", ["equestrian"], "Horse + Rider", "medium", "sport", 13),
    ("🥏⛳", "Disc Golf", ["disc golf"], "Disc + Golf flag", "medium", "sport", 14),
    ("⬜🌊🛶", "White Water Rafting", ["white water rafting"], "White + Water + Raft", "medium", "sport", 15),
    ("💧🤽", "Water Polo", ["water polo"], "Water + Polo player", "medium", "sport", 16),
    ("⛸️💃", "Figure Skating", ["figure skating"], "Skate + Dance", "medium", "sport", 17),
    # === HARD (16) ===
    ("🏸💨", "Badminton", ["badminton"], "Shuttlecock + Wind", "hard", "sport", 1),
    ("⛷️🎯", "Biathlon", ["biathlon"], "Ski + Target", "hard", "sport", 2),
    ("🚴🏔️", "Mountain Biking", ["mountain biking"], "Bike + Mountain", "hard", "sport", 3),
    ("🏹🐴", "Mounted Archery", ["mounted archery"], "Bow + Horse", "hard", "sport", 4),
    ("🛷❄️", "Luge", ["luge"], "Sled + Snow", "hard", "sport", 5),
    ("🏇🔨⚽", "Polo", ["polo"], "Horse + Mallet + Ball", "hard", "sport", 6),
    ("🏊👯‍♀️🎵", "Synchronized Swimming", ["synchronized swimming","synchro swimming"], "Swim + Sync + Music", "hard", "sport", 7),
    ("🏊🤺🏃🔫🐴", "Modern Pentathlon", ["modern pentathlon","pentathlon"], "Swim + Fence + Run + Shoot + Ride", "hard", "sport", 8),
    ("🧗🧊", "Ice Climbing", ["ice climbing"], "Climb + Ice", "hard", "sport", 9),
    ("🛶🌊", "Kayaking", ["kayaking"], "Kayak + Water", "hard", "sport", 10),
    ("🏌️🌙", "Night Golf", ["night golf"], "Golf + Moon", "hard", "sport", 11),
    ("🤸🏢", "Parkour", ["parkour"], "Acrobat + Building", "hard", "sport", 12),
    ("🎿🪂", "Ski Jumping", ["ski jumping"], "Ski + Parachute", "hard", "sport", 13),
    ("🤿🔱🐟", "Spearfishing", ["spearfishing","spear fishing"], "Diver + Trident + Fish", "hard", "sport", 14),
    ("🚣‍♂️🏔️💨", "Whitewater Kayaking", ["whitewater kayaking","kayaking"], "Row + Mountain + Rapids", "hard", "sport", 15),
    ("🐎🏃💨", "Chariot Racing", ["chariot racing"], "Horse + Running + Speed", "hard", "sport", 16),
]

BOOKS = [
    # === EASY (17) ===
    ("📖🪱", "Bookworm", ["bookworm","book worm"], "Book + Worm", "easy", "word", 1),
    ("📝📖", "Notebook", ["notebook","note book"], "Note + Book", "easy", "word", 2),
    ("🐈🎩", "The Cat in the Hat", ["the cat in the hat","cat in the hat"], "Cat + Hat", "easy", "children", 3),
    ("🐻🧸", "Winnie the Pooh", ["winnie the pooh"], "Bear + Teddy", "easy", "children", 4),
    ("🕷️🕸️", "Charlotte's Web", ["charlottes web","charlotte's web"], "Spider + Web", "easy", "children", 5),
    ("🐒🌴", "Curious George", ["curious george"], "Monkey + Trees", "easy", "children", 6),
    ("🌈🐟", "Rainbow Fish", ["rainbow fish"], "Rainbow + Fish", "easy", "children", 7),
    ("🧙‍♂️🏰", "Harry Potter", ["harry potter"], "Wizard + Castle", "easy", "fantasy", 8),
    ("🐉🔥", "The Hobbit", ["the hobbit","hobbit"], "Dragon + Fire", "easy", "fantasy", 9),
    ("🐰⏰", "Alice in Wonderland", ["alice in wonderland"], "Rabbit + Clock", "easy", "children", 10),
    ("🏴‍☠️🏝️", "Treasure Island", ["treasure island"], "Pirate + Island", "easy", "adventure", 11),
    ("🐋📖", "Moby Dick", ["moby dick"], "Whale + Book", "easy", "classic", 12),
    ("📖🐛", "The Very Hungry Caterpillar", ["the very hungry caterpillar","hungry caterpillar"], "Book + Caterpillar", "easy", "children", 13),
    ("🦁🧙‍♂️🚪", "The Lion, the Witch and the Wardrobe", ["the lion the witch and the wardrobe","narnia"], "Lion + Witch + Door", "easy", "fantasy", 14),
    ("🧑‍🚀🔴", "The Martian", ["the martian","martian"], "Astronaut + Red planet", "easy", "sci-fi", 15),
    ("🐕🌨️", "White Fang", ["white fang"], "Dog + Snow", "easy", "adventure", 16),
    ("👦🐕", "Old Yeller", ["old yeller"], "Boy + Dog", "easy", "classic", 17),
    # === MEDIUM (17) ===
    ("👑💍🧙", "Lord of the Rings", ["lord of the rings","lotr"], "Crown + Ring + Wizard", "medium", "fantasy", 1),
    ("📞🐺🌲", "The Call of the Wild", ["the call of the wild","call of the wild"], "Phone + Wolf + Forest", "medium", "adventure", 2),
    ("👴🌊🐟", "The Old Man and the Sea", ["the old man and the sea"], "Old man + Sea + Fish", "medium", "classic", 3),
    ("🐷🏡🐄", "Animal Farm", ["animal farm"], "Pig + Farm + Cow", "medium", "classic", 4),
    ("🍫🏭👦", "Charlie and the Chocolate Factory", ["charlie and the chocolate factory"], "Chocolate + Factory + Boy", "medium", "children", 5),
    ("🧛🏰🌙", "Dracula", ["dracula"], "Vampire + Castle + Moon", "medium", "horror", 6),
    ("👻🏚️", "The Haunting of Hill House", ["the haunting of hill house","haunting of hill house"], "Ghost + House", "medium", "horror", 7),
    ("🔥🚒📖", "Fahrenheit 451", ["fahrenheit 451"], "Fire + Firetruck + Book", "medium", "sci-fi", 8),
    ("💧🚢⬇️", "Watership Down", ["watership down"], "Water + Ship + Down", "medium", "adventure", 9),
    ("🐢🐢🥷🍕", "Teenage Mutant Ninja Turtles", ["teenage mutant ninja turtles","tmnt"], "Turtles + Ninja + Pizza", "medium", "comic", 10),
    ("🌹📖", "The Name of the Rose", ["the name of the rose"], "Rose + Book", "medium", "classic", 11),
    ("🕶️🔫🍸", "James Bond", ["james bond","007"], "Sunglasses + Gun + Martini", "medium", "spy", 12),
    ("🦁🔮🚪❄️", "The Chronicles of Narnia", ["the chronicles of narnia","narnia"], "Lion + Magic + Door + Snow", "medium", "fantasy", 13),
    ("👁️⛓️📺", "1984", ["1984"], "Eye + Chains + Screen", "medium", "classic", 14),
    ("🐭🐭👨🌾", "Of Mice and Men", ["of mice and men"], "Mice + Man + Farm", "medium", "classic", 15),
    ("🐉👦🗡️", "Eragon", ["eragon"], "Dragon + Boy + Sword", "medium", "fantasy", 16),
    ("🌑🐺", "New Moon", ["new moon"], "Dark moon + Wolf", "medium", "fantasy", 17),
    # === HARD (16) ===
    ("🍽️🏹👧", "The Hunger Games", ["the hunger games","hunger games"], "Hunger + Bow + Girl", "hard", "sci-fi", 1),
    ("⚖️🐦", "To Kill a Mockingbird", ["to kill a mockingbird"], "Justice + Bird", "hard", "classic", 2),
    ("🧪⚡💀", "Frankenstein", ["frankenstein"], "Lab + Lightning + Skull", "hard", "horror", 3),
    ("🏝️🐚🪰", "Lord of the Flies", ["lord of the flies"], "Island + Shell + Fly", "hard", "classic", 4),
    ("👍🚗🌌", "The Hitchhiker's Guide to the Galaxy", ["hitchhikers guide to the galaxy","the hitchhiker's guide to the galaxy"], "Thumb + Car + Galaxy", "hard", "sci-fi", 5),
    ("🌙🎪", "The Night Circus", ["the night circus","night circus"], "Moon + Circus", "hard", "fantasy", 6),
    ("⏰🔧", "The Time Machine", ["the time machine","time machine"], "Clock + Machine", "hard", "sci-fi", 7),
    ("🏴‍☠️🧚🪝", "Peter Pan", ["peter pan"], "Pirate + Fairy + Hook", "hard", "children", 8),
    ("🧬🦕🦖", "Jurassic Park", ["jurassic park"], "DNA + Dinosaurs", "hard", "sci-fi", 9),
    ("🌊⛵🐯", "Life of Pi", ["life of pi"], "Ocean + Boat + Tiger", "hard", "adventure", 10),
    ("👗💃🏰", "Pride and Prejudice", ["pride and prejudice"], "Dress + Dance + Manor", "hard", "classic", 11),
    ("🔢🏔️🗡️", "The Count of Monte Cristo", ["the count of monte cristo","count of monte cristo"], "Count + Mountain + Sword", "hard", "classic", 12),
    ("⏰👑🗡️", "The Once and Future King", ["the once and future king"], "Time + King + Sword", "hard", "fantasy", 13),
    ("🐦✋🌳", "A Bird in the Hand", ["a bird in the hand"], "Bird + Hand + Tree", "hard", "classic", 14),
    ("🏠🃏🃏", "House of Cards", ["house of cards"], "House + Cards", "hard", "thriller", 15),
    ("💀🚪👔", "Skeleton in the Closet", ["skeleton in the closet"], "Skull + Door + Suit", "hard", "mystery", 16),
]

TV = [
    # === EASY (17) ===
    ("🐉🔥👑", "Game of Thrones", ["game of thrones"], "Dragon + Fire + Crown", "easy", "fantasy", 1),
    ("☕👫", "Friends", ["friends"], "Coffee + Friends", "easy", "comedy", 2),
    ("🏢📋", "The Office", ["the office","office"], "Office + Clipboard", "easy", "comedy", 3),
    ("🧟‍♂️🚶", "The Walking Dead", ["the walking dead","walking dead"], "Zombie + Walking", "easy", "horror", 4),
    ("👨‍🍳💊", "Breaking Bad", ["breaking bad"], "Cook + Drugs", "easy", "drama", 5),
    ("👽🛸", "The X-Files", ["the x-files","x-files","x files"], "Alien + UFO", "easy", "sci-fi", 6),
    ("🏠📺", "Full House", ["full house"], "House + TV", "easy", "comedy", 7),
    ("👨‍👩‍👧‍👦👫", "Modern Family", ["modern family"], "Family + Couple", "easy", "comedy", 8),
    ("🦇🌃", "Gotham", ["gotham"], "Bat + City", "easy", "drama", 9),
    ("👨‍⚕️🏥", "Grey's Anatomy", ["greys anatomy","grey's anatomy"], "Doctor + Hospital", "easy", "drama", 10),
    ("🏝️🌴", "Survivor", ["survivor"], "Island + Palm tree", "easy", "reality", 11),
    ("🔫🤠", "Westworld", ["westworld","west world"], "Gun + Cowboy", "easy", "sci-fi", 12),
    ("🌌⭐🚀", "Star Trek", ["star trek"], "Space + Star + Rocket", "easy", "sci-fi", 13),
    ("🔍🐕👻", "Scooby-Doo", ["scooby-doo","scooby doo"], "Search + Dog + Ghost", "easy", "animated", 14),
    ("🦸‍♂️🦸‍♀️", "The Boys", ["the boys"], "Superheroes", "easy", "action", 15),
    ("🐻🌲", "Yellowstone", ["yellowstone"], "Bear + Trees", "easy", "drama", 16),
    ("👶📺", "Baby TV", ["baby tv"], "Baby + TV", "easy", "children", 17),
    # === MEDIUM (17) ===
    ("⬛🪞", "Black Mirror", ["black mirror"], "Black + Mirror", "medium", "sci-fi", 1),
    ("⬛📃", "The Blacklist", ["the blacklist","blacklist"], "Black + List", "medium", "thriller", 2),
    ("👑🎭🏰", "The Crown", ["the crown"], "Crown + Drama + Castle", "medium", "drama", 3),
    ("🧛💉🩸", "True Blood", ["true blood"], "Vampire + Blood", "medium", "horror", 4),
    ("🏠🐉👑", "House of the Dragon", ["house of the dragon"], "House + Dragon + Crown", "medium", "fantasy", 5),
    ("🏢👔💼", "Suits", ["suits"], "Office + Tie + Briefcase", "medium", "drama", 6),
    ("🕵️🔍🎻", "Sherlock", ["sherlock"], "Detective + Magnifier + Violin", "medium", "mystery", 7),
    ("🛸👽🌽🚲", "Stranger Things", ["stranger things"], "UFO + Alien + Bikes", "medium", "sci-fi", 8),
    ("🌍🧟🍄", "The Last of Us", ["the last of us"], "World + Zombie + Mushroom", "medium", "drama", 9),
    ("🇺🇸👻🏚️", "American Horror Story", ["american horror story"], "America + Ghost + House", "medium", "horror", 10),
    ("🔥🪰🚀", "Firefly", ["firefly"], "Fire + Fly + Rocket", "medium", "sci-fi", 11),
    ("🐍🥋🤛", "Cobra Kai", ["cobra kai"], "Snake + Karate + Fist", "medium", "drama", 12),
    ("☎️👨‍⚖️", "Better Call Saul", ["better call saul"], "Phone + Lawyer", "medium", "drama", 13),
    ("🌊🐚🧽", "SpongeBob SquarePants", ["spongebob squarepants","spongebob"], "Ocean + Sponge", "medium", "animated", 14),
    ("👩‍🔬🧪🔪", "Dexter", ["dexter"], "Scientist + Lab + Knife", "medium", "thriller", 15),
    ("🎵🧊🔥", "A Song of Ice and Fire", ["a song of ice and fire"], "Song + Ice + Fire", "medium", "fantasy", 16),
    ("👸♟️", "The Queen's Gambit", ["the queens gambit","the queen's gambit","queens gambit"], "Queen + Chess", "medium", "drama", 17),
    # === HARD (16) ===
    ("🦑🎮", "Squid Game", ["squid game"], "Squid + Game", "hard", "thriller", 1),
    ("⬛⛵🏴‍☠️", "Black Sails", ["black sails"], "Black + Sail + Pirate", "hard", "adventure", 2),
    ("🧠🍽️🔪", "Hannibal", ["hannibal"], "Brain + Dinner + Knife", "hard", "thriller", 3),
    ("✈️🏝️💥", "Lost", ["lost"], "Plane + Island + Crash", "hard", "drama", 4),
    ("🌑👨‍👩‍👧‍👦⏰", "Dark", ["dark"], "Darkness + Family + Time", "hard", "sci-fi", 5),
    ("❄️🏔️💰", "Fargo", ["fargo"], "Snow + Mountain + Money", "hard", "thriller", 6),
    ("🟡🐝✈️", "Yellowjackets", ["yellowjackets","yellow jackets"], "Yellow + Bee + Plane", "hard", "thriller", 7),
    ("👩🔴🏛️", "The Handmaid's Tale", ["the handmaids tale","the handmaid's tale","handmaids tale"], "Woman + Red + Building", "hard", "drama", 8),
    ("🔑🏰🚪", "Locke & Key", ["locke and key","locke & key"], "Key + Castle + Door", "hard", "fantasy", 9),
    ("🌙🦇🧛", "What We Do in the Shadows", ["what we do in the shadows"], "Night + Bat + Vampire", "hard", "comedy", 10),
    ("👀📺🔪", "You", ["you"], "Eyes + TV + Knife", "hard", "thriller", 11),
    ("🏠🌍🕵️", "Homeland", ["homeland"], "Home + Land + Spy", "hard", "thriller", 12),
    ("🃏🎭😂", "Joker", ["joker"], "Joker + Mask + Laugh", "hard", "drama", 13),
    ("🐺🌙👦", "Teen Wolf", ["teen wolf"], "Wolf + Moon + Boy", "hard", "horror", 14),
    ("🌊🐉🏝️", "Sea Dragon", ["sea dragon"], "Ocean + Dragon + Island", "hard", "fantasy", 15),
    ("🏠🔥🚒", "Chicago Fire", ["chicago fire"], "House + Fire + Firetruck", "hard", "drama", 16),
]

# Celebs pack: only celebrities/bands whose names break down into literal emoji words
CELEBS = [
    # === EASY (17) ===
    ("🧊🎲", "Ice Cube", ["ice cube"], "Ice + Cube", "easy", "rapper", 1),
    ("🃏⬛", "Jack Black", ["jack black"], "Jack + Black", "easy", "actor", 2),
    ("🐅🌲", "Tiger Woods", ["tiger woods"], "Tiger + Woods", "easy", "athlete", 3),
    ("🪨", "The Rock", ["the rock","dwayne johnson"], "Rock", "easy", "actor", 4),
    ("🍦🧊", "Vanilla Ice", ["vanilla ice"], "Vanilla + Ice", "easy", "rapper", 5),
    ("🔍🐕", "Snoop Dogg", ["snoop dogg","snoop dog"], "Snoop + Dog", "easy", "rapper", 6),
    ("5️⃣0️⃣🪙", "50 Cent", ["50 cent"], "50 + Cent", "easy", "rapper", 7),
    ("🔫🌹", "Guns N' Roses", ["guns n roses","guns and roses","guns n' roses"], "Gun + Rose", "easy", "band", 8),
    ("💀🐭", "Deadmau5", ["deadmau5","dead mouse"], "Dead + Mouse", "easy", "dj", 9),
    ("🟢📅", "Green Day", ["green day"], "Green + Day", "easy", "band", 10),
    ("🧊🍵", "Ice-T", ["ice-t","ice t"], "Ice + Tea", "easy", "rapper", 11),
    ("🐕", "Pitbull", ["pitbull","pit bull"], "Pitbull dog", "easy", "rapper", 12),
    ("2️⃣⛓️", "2 Chainz", ["2 chainz","two chainz"], "Two + Chains", "easy", "rapper", 13),
    ("🦆", "Drake", ["drake"], "Drake (male duck)", "easy", "rapper", 14),
    ("👑🐝", "Beyonce", ["beyonce","queen bee","queen b"], "Queen + Bee", "easy", "musician", 15),
    ("🪓🌹", "Axl Rose", ["axl rose"], "Axe + Rose", "easy", "musician", 16),
    ("❄️🐒", "Arctic Monkeys", ["arctic monkeys"], "Snow + Monkeys", "easy", "band", 17),
    # === MEDIUM (17) ===
    ("🔴🌶️🌶️", "Red Hot Chili Peppers", ["red hot chili peppers"], "Red + Hot + Chili Peppers", "medium", "band", 1),
    ("🦪🫙", "Pearl Jam", ["pearl jam"], "Pearl + Jam", "medium", "band", 2),
    ("⬛🔑🔑", "The Black Keys", ["the black keys","black keys"], "Black + Keys", "medium", "band", 3),
    ("👻👨", "Ghostface Killah", ["ghostface killah","ghostface"], "Ghost + Face", "medium", "rapper", 4),
    ("👶🌧️", "Lil Wayne", ["lil wayne"], "Little + Rain (Wayne)", "medium", "rapper", 5),
    ("📮🍈", "Post Malone", ["post malone"], "Post + Melon", "medium", "rapper", 6),
    ("⬛🕯️", "Black Sabbath", ["black sabbath"], "Black + Candle", "medium", "band", 7),
    ("🔊🌻", "Soundgarden", ["soundgarden","sound garden"], "Sound + Garden", "medium", "band", 8),
    ("🤖🔫", "Machine Gun Kelly", ["machine gun kelly","mgk"], "Machine + Gun", "medium", "rapper", 9),
    ("👑🦁", "Kings of Leon", ["kings of leon"], "King + Lion", "medium", "band", 10),
    ("🔩👰", "Iron Maiden", ["iron maiden"], "Iron + Maiden", "medium", "band", 11),
    ("👩⛓️", "Alice in Chains", ["alice in chains"], "Woman + Chains", "medium", "band", 12),
    ("🎲🎤", "Chance the Rapper", ["chance the rapper"], "Dice/Chance + Microphone", "medium", "rapper", 13),
    ("⚔️👦", "Soulja Boy", ["soulja boy"], "Soldier + Boy", "medium", "rapper", 14),
    ("👜🦁", "Gucci Mane", ["gucci mane"], "Bag + Mane", "medium", "rapper", 15),
    ("👦🦌", "Young Buck", ["young buck"], "Young + Buck (deer)", "medium", "rapper", 16),
    ("👶⛽", "Lil Pump", ["lil pump"], "Little + Pump", "medium", "rapper", 17),
    # === HARD (16) ===
    ("🃏⬜", "Jack White", ["jack white"], "Jack + White", "hard", "musician", 1),
    ("🪵🏞️", "Justin Timberlake", ["justin timberlake"], "Timber + Lake", "hard", "musician", 2),
    ("📜🔨", "Will Smith", ["will smith"], "Will + Smith (hammer)", "hard", "actor", 3),
    ("🍎💡", "Steve Jobs", ["steve jobs"], "Apple + Lightbulb", "hard", "tech", 4),
    ("🧪🧠", "Albert Einstein", ["albert einstein","einstein"], "Science + Brain", "hard", "scientist", 5),
    ("🔔☎️", "Alexander Graham Bell", ["alexander graham bell"], "Bell + Phone", "hard", "inventor", 6),
    ("🎩🐇", "David Copperfield", ["david copperfield"], "Hat + Rabbit (magic)", "hard", "magician", 7),
    ("🪨🎈", "Led Zeppelin", ["led zeppelin"], "Lead (rock) + Airship", "hard", "band", 8),
    ("🐝🌊🐝", "B.o.B", ["b.o.b","bob"], "B + Ocean + B", "hard", "rapper", 9),
    ("⬛🐝👁️🍑", "Black Eyed Peas", ["black eyed peas"], "Black + Eye + Peas", "hard", "band", 10),
    ("🦁👑🌅", "Mufasa", ["mufasa"], "Lion + King + Sunrise", "hard", "character", 11),
    ("🐻🧔", "Bear Grylls", ["bear grylls"], "Bear + Grills", "hard", "tv", 12),
    ("🎸🔪", "Slash", ["slash"], "Guitar + Slash/Cut", "hard", "musician", 13),
    ("🐝👧🐝", "Bee Gees", ["bee gees"], "Bee + G + Bee", "hard", "band", 14),
    ("⬛🐻", "Jack Bear", ["black bear","blackbear"], "Black + Bear", "hard", "musician", 15),
    ("🌲🔥🎤", "Alicia Keys", ["alicia keys"], "A + Keys (piano)", "hard", "musician", 16),
]

PHRASES = [
    # === EASY (17) ===
    ("⏰✈️", "Time Flies", ["time flies"], "Clock + Plane", "easy", "saying", 1),
    ("🌧️🐱🐕", "Raining Cats and Dogs", ["raining cats and dogs"], "Rain + Cat + Dog", "easy", "saying", 2),
    ("🍒🔝", "Cherry on Top", ["cherry on top"], "Cherry + Top", "easy", "saying", 3),
    ("💔💔", "Heartbreak", ["heartbreak","heart break"], "Broken hearts", "easy", "saying", 4),
    ("🔥🏃", "On Fire", ["on fire"], "Fire + Running", "easy", "saying", 5),
    ("🐝🧵", "Busy Bee", ["busy bee"], "Bee + Busy", "easy", "saying", 6),
    ("🧊❄️", "Ice Cold", ["ice cold"], "Ice + Cold", "easy", "saying", 7),
    ("☁️9️⃣", "Cloud Nine", ["cloud nine","cloud 9"], "Cloud + Nine", "easy", "saying", 8),
    ("👁️👁️", "Eye to Eye", ["eye to eye"], "Eye + Eye", "easy", "saying", 9),
    ("🏃💨", "Run Like the Wind", ["run like the wind"], "Run + Wind", "easy", "saying", 10),
    ("🎂🍒", "Icing on the Cake", ["icing on the cake"], "Cake + Cherry", "easy", "saying", 11),
    ("💡💡", "Bright Idea", ["bright idea"], "Lightbulb + Lightbulb", "easy", "saying", 12),
    ("🐝📐", "Beeline", ["beeline","bee line"], "Bee + Line", "easy", "saying", 13),
    ("🌞😊", "Bright Side", ["bright side","look on the bright side"], "Sun + Smile", "easy", "saying", 14),
    ("🌈🦄", "Unicorn", ["unicorn"], "Rainbow + Unicorn", "easy", "saying", 15),
    ("🌊⬇️", "Downpour", ["downpour","down pour"], "Wave + Down", "easy", "saying", 16),
    ("⭐⭐⭐", "Three Stars", ["three stars"], "Three stars", "easy", "saying", 17),
    # === MEDIUM (17) ===
    ("🐘🏠", "Elephant in the Room", ["elephant in the room"], "Elephant + Room", "medium", "saying", 1),
    ("🐂👁️🎯", "Bullseye", ["bullseye","bull's eye","bulls eye"], "Bull + Eye + Target", "medium", "saying", 2),
    ("🐔🥚❓", "Which Came First", ["which came first","chicken or egg"], "Chicken + Egg + Question", "medium", "saying", 3),
    ("🍎🌳⬇️", "Apple Doesn't Fall Far", ["apple doesnt fall far","apple doesn't fall far from the tree"], "Apple + Tree + Down", "medium", "saying", 4),
    ("🐺🐑👔", "Wolf in Sheep's Clothing", ["wolf in sheeps clothing","wolf in sheep's clothing"], "Wolf + Sheep + Suit", "medium", "saying", 5),
    ("🐱👜", "Cat's Out of the Bag", ["cats out of the bag","cat's out of the bag"], "Cat + Bag", "medium", "saying", 6),
    ("🔥🧊", "Hot and Cold", ["hot and cold"], "Fire + Ice", "medium", "saying", 7),
    ("🪨⬇️", "Rock Bottom", ["rock bottom"], "Rock + Down", "medium", "saying", 8),
    ("🌙🎯", "Shoot for the Moon", ["shoot for the moon"], "Moon + Target", "medium", "saying", 9),
    ("🗝️🚪", "Key to Success", ["key to success"], "Key + Door", "medium", "saying", 10),
    ("💎🏜️", "Diamond in the Rough", ["diamond in the rough"], "Diamond + Desert", "medium", "saying", 11),
    ("🎭🎭", "Two-Faced", ["two-faced","two faced"], "Two masks", "medium", "saying", 12),
    ("🐎💧", "You Can Lead a Horse to Water", ["you can lead a horse to water"], "Horse + Water", "medium", "saying", 13),
    ("🐦🪨🐦", "Kill Two Birds with One Stone", ["kill two birds with one stone"], "Bird + Stone + Bird", "medium", "saying", 14),
    ("☁️✨☀️", "Every Cloud Has a Silver Lining", ["every cloud has a silver lining"], "Cloud + Silver + Sun", "medium", "saying", 15),
    ("🐟🐟🌊", "Plenty of Fish in the Sea", ["plenty of fish in the sea","theres plenty of fish in the sea"], "Fish + Fish + Sea", "medium", "saying", 16),
    ("🧎💍", "On Bended Knee", ["on bended knee"], "Kneeling + Ring", "medium", "saying", 17),
    # === HARD (16) ===
    ("🐢🐇🏁", "Slow and Steady Wins the Race", ["slow and steady wins the race"], "Turtle + Rabbit + Finish line", "hard", "saying", 1),
    ("🔑🗑️", "Throw Away the Key", ["throw away the key"], "Key + Trash", "hard", "saying", 2),
    ("🐦✋🌳", "A Bird in the Hand", ["a bird in the hand"], "Bird + Hand + Tree", "hard", "saying", 3),
    ("🐟📏🏠", "Big Fish in a Small Pond", ["big fish in a small pond"], "Fish + Ruler + House (small)", "hard", "saying", 4),
    ("🏠🃏🃏", "House of Cards", ["house of cards"], "House + Cards", "hard", "saying", 5),
    ("🥫🐛🐛", "Can of Worms", ["can of worms"], "Can + Worms", "hard", "saying", 6),
    ("⛵🚫🪨", "Don't Rock the Boat", ["dont rock the boat","don't rock the boat"], "Boat + No + Rock", "hard", "saying", 7),
    ("🐘🧠", "Memory of an Elephant", ["memory of an elephant"], "Elephant + Brain", "hard", "saying", 8),
    ("💀🚪👔", "Skeleton in the Closet", ["skeleton in the closet"], "Skull + Door + Suit", "hard", "saying", 9),
    ("✋🍪🫙", "Hand in the Cookie Jar", ["hand in the cookie jar","caught with hand in the cookie jar"], "Hand + Cookie + Jar", "hard", "saying", 10),
    ("🦆💧", "Like Water Off a Duck's Back", ["like water off a ducks back","water off a duck's back"], "Duck + Water", "hard", "saying", 11),
    ("🐍🌿", "Snake in the Grass", ["snake in the grass"], "Snake + Grass", "hard", "saying", 12),
    ("❄️❤️", "Cold Hearted", ["cold hearted"], "Snowflake + Heart", "hard", "saying", 13),
    ("🦁❤️", "Lionheart", ["lionheart","lion heart"], "Lion + Heart", "hard", "saying", 14),
    ("🐸💚", "It's Not Easy Being Green", ["its not easy being green","it's not easy being green"], "Frog + Green", "hard", "saying", 15),
    ("🐦🐦☝️🪨", "Two Birds One Stone", ["two birds one stone","kill two birds with one stone"], "Birds + One + Stone", "hard", "saying", 16),
]

ALL_PACKS = [
    ("pack_movies", MOVIES),
    ("pack_songs", SONGS),
    ("pack_food", FOOD),
    ("pack_animals", ANIMALS),
    ("pack_places", PLACES),
    ("pack_sports", SPORTS),
    ("pack_books", BOOKS),
    ("pack_tv", TV),
    ("pack_celebs", CELEBS),
    ("pack_phrases", PHRASES),
]

def build_puzzle(idx, pack_id, data):
    emoji, answer, accepted, hint, diff, cat, order = data
    # Describe the emojis for accessibility
    return {
        "id": f"puz_{idx:03d}",
        "pack_id": pack_id,
        "emoji_clue": emoji,
        "canonical_answer": answer,
        "accepted_answers": accepted,
        "hint": hint,
        "difficulty": diff,
        "category": cat,
        "accessibility_label": f"{emoji} — {hint}",
        "level_order": order
    }

def main():
    puzzles = []
    idx = 1
    for pack_id, pack_data in ALL_PACKS:
        for data in pack_data:
            puzzles.append(build_puzzle(idx, pack_id, data))
            idx += 1

    with open("data/seed-puzzles.json", "w") as f:
        json.dump(puzzles, f, indent=2, ensure_ascii=False)

    # Stats
    total = len(puzzles)
    by_pack = {}
    for p in puzzles:
        by_pack[p["pack_id"]] = by_pack.get(p["pack_id"], 0) + 1

    print(f"Generated {total} puzzles")
    for pack, count in by_pack.items():
        print(f"  {pack}: {count}")

    # Check for duplicate answers within same pack
    seen = {}
    dupes = []
    for p in puzzles:
        key = (p["pack_id"], p["canonical_answer"].lower())
        if key in seen:
            dupes.append((p["id"], seen[key], p["canonical_answer"]))
        seen[key] = p["id"]

    if dupes:
        print(f"\nWARNING: {len(dupes)} duplicate answers found:")
        for d in dupes:
            print(f"  {d[0]} and {d[1]}: {d[2]}")
    else:
        print("\nNo duplicate answers within packs!")

if __name__ == "__main__":
    main()
